[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Specify the Python versions and platforms you want to build for
build = "cp3[9-12]-*"